# -*- coding: utf-8 -*-
"""찐찐막 딥러닝 완성!!!

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/136vl8iUbZNkHs35vrYPXQljjhdt-LBmz
"""

# ========================================================
# 1. 환경 세팅 및 패키지 설치 + 엑셀 엔진(openpyxl) 설치
# ========================================================
import sys
import subprocess
import os

print("📦 1단계: 필수 패키지 및 엑셀 리더 엔진 설치 중...")
subprocess.check_call([sys.executable, "-m", "pip", "install", "--upgrade", "pip"])
# 엑셀(.xlsx) 파일 분석을 위해 openpyxl 패키지를 확실하게 설치합니다.
subprocess.check_call([sys.executable, "-m", "pip", "install", "pyarrow", "datasets", "transformers[torch]", "accelerate", "evaluate", "openpyxl", "-U"])
print("✅ 패키지 설치 완료!\n")

import pandas as pd
import numpy as np
import torch
import torch.nn.functional as F
from sklearn.model_selection import train_test_split
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer
from datasets import Dataset
import evaluate
import gc

# 메모리 찌꺼기 정리 (12.7GB RAM 방어)
gc.collect()
torch.cuda.empty_cache()

# ========================================================
# 2. 업로드된 엑셀 파일 자동 검색 및 철저한 예외 처리 로드
# ========================================================
target_dir = '/content'
# 'embedding_result' 단어가 들어간 모든 파일 검색
files = [f for f in os.listdir(target_dir) if 'embedding_result' in f]

if not files:
    raise FileNotFoundError("❌ 코랩 왼쪽 폴더에 'embedding_result' 파일이 보이지 않습니다! 파일을 꼭 업로드한 뒤 다시 실행해 주세요.")

selected_file = files[0]
full_path = os.path.join(target_dir, selected_file)
print(f"📂 발견된 데이터 파일 로드 시도: {full_path}")

# [🛠️ 초강력 파일 읽기 조치]
# 파일 확장자가 .csv로 되어 있더라도 엑셀 구조일 수 있으므로, read_excel과 read_csv를 교차 시도하여 무조건 읽어냅니다.
try:
    if selected_file.endswith('.csv'):
        # csv로 시도해보고 실패하면 excel로 우회
        try:
            df = pd.read_csv(full_path)
            # 만약 잘못 읽어서 컬럼이 깨졌다면 엑셀로 재시도
            if len(df.columns) <= 1:
                raise ValueError
        except:
            df = pd.read_excel(full_path, engine='openpyxl')
    else:
        df = pd.read_excel(full_path, engine='openpyxl')
    print("✅ 파일 정상 로드 성공!")
except Exception as e:
    raise RuntimeError(f"❌ 파일을 읽는 데 실패했습니다. 파일이 손상되었거나 형식이 올바르지 않습니다. 오류 내용: {e}")

# ========================================================
# 3. 데이터 분할 및 레이블 변환 (is_discriminatory 정답 열 적용)
# ========================================================
print("📊 2단계: 데이터 전처리 및 분할 시작...")

# 문장이 들어있는 열 지정 ('tokens')
X = df['tokens'].values

# [핵심] True/False 혹은 문자열, 숫자로 되어있을 정답 열을 0과 1의 정수형 숫자로 정확히 매핑합니다.
df['label_clean'] = df['is_discriminatory'].map({False: 0, True: 1, 'False': 0, 'True': 1, 0: 0, 1: 1})
y = df['label_clean'].astype(int).values

num_labels = 2  # 정상(0) vs 차별/비하(1)

# 학습/검증/테스트 데이터 분할 (8:1:1)
X_train, X_tmp, y_train, y_tmp = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
X_val, X_test, y_val, y_test = train_test_split(X_tmp, y_tmp, test_size=0.5, random_state=42, stratify=y_tmp)

# ========================================================
# 4. 모델 정의 및 토크나이저 로드 (klue/roberta-large)
# ========================================================
model_name = "klue/roberta-large"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=num_labels)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
print(f"🖥️ 사용 중인 장치: {device} (🚀 엑셀 완벽 대응 + 진짜 정답지 반영 완료)")

# ========================================================
# 5. 허깅페이스 데이터셋 변환 및 토큰화
# ========================================================
def prepare_text(X):
    return [" ".join(text) if isinstance(text, list) else str(text) for text in X]

train_ds = Dataset.from_dict({"text": prepare_text(X_train), "label": y_train})
val_ds = Dataset.from_dict({"text": prepare_text(X_val), "label": y_val})
test_ds = Dataset.from_dict({"text": prepare_text(X_test), "label": y_test})

def tokenize_function(examples):
    return tokenizer(examples["text"], padding="max_length", truncation=True, max_length=128)

tokenized_train = train_ds.map(tokenize_function, batched=True, load_from_cache_file=False)
tokenized_val = val_ds.map(tokenize_function, batched=True, load_from_cache_file=False)
tokenized_test = test_ds.map(tokenize_function, batched=True, load_from_cache_file=False)

# RAM 부족 방지를 위해 대용량 원본 변수들 즉시 메모리 해제
del df, train_ds, val_ds, test_ds
gc.collect()

# ========================================================
# 6. 평가 지표 설정
# ========================================================
metric = evaluate.load("accuracy")
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return metric.compute(predictions=predictions, references=labels)

# ========================================================
# 7. 초고속 학습 환경 설정 (2~3분 컷 8배속 세팅)
# ========================================================
training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,

    per_device_train_batch_size=8,
    per_device_eval_batch_size=32,
    gradient_accumulation_steps=1,
    fp16=True if torch.cuda.is_available() else False,

    dataloader_num_workers=0,

    num_train_epochs=3,
    weight_decay=0.01,
    load_best_model_at_end=True,
    logging_steps=5,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_val,
    compute_metrics=compute_metrics,
)

print("\n🚀 3단계: 진짜 엑셀 정답지를 기반으로 초고속 훈련을 시작합니다!")
trainer.train()

# ========================================================
# 8. 최종 평가 및 모델 저장
# ========================================================
print("\n=== 🎯 4단계: 최종 평가 데이터셋 결과 ===")
final_result = trainer.evaluate(tokenized_test)
print(f"🥇 최종 정확도(Test Accuracy): {final_result['eval_accuracy'] * 100:.2f}%")

model_path = "./my_roberta_model"
trainer.save_model(model_path)
tokenizer.save_pretrained(model_path)
print(f"💾 학습 완료된 모델 저장이 완료되었습니다. 폴더 위치: {model_path}\n")

# ========================================================
# 9. 실시간 테스트 (원하셨던 직관적인 한글 문구 출력 버전)
# ========================================================
print("🔮 5단계: 새로운 문장 실시간 테스트 진행")
model.eval()

# 예측 레이블을 직관적인 문구로 매핑
LABEL_MAPPING = {
    0: "✅ 평범한 대답!",
    1: "⚠️ 남녀차별 발언 확인!"
}

def predict_discrimination(texts):
    inputs = tokenizer(texts, padding=True, truncation=True, max_length=128, return_tensors="pt")
    inputs = {k: v.to(device) for k, v in inputs.items()}

    with torch.no_grad():
        outputs = model(**inputs)
        logits = outputs.logits
        probabilities = F.softmax(logits, dim=-1).cpu().numpy()
        predictions = torch.argmax(logits, dim=-1).cpu().numpy()

    for text, pred, prob in zip(texts, predictions, probabilities):
        label = LABEL_MAPPING.get(pred, f"알 수 없음 ({pred})")
        confidence = prob[pred] * 100
        print(f"💬 입력 문장: {text}")
        print(f"📊 예측 결과: {label} (확신도: {confidence:.2f}%)")
        print("-" * 50)

test_sentences = [
    "오늘 날씨가 정말 화창하고 기분이 좋네요.",
    "정말 무대 매너도 꽝이고 보기 싫다.",
    "차별 없는 세상을 만들기 위해 다 같이 노력합시다.",
    "틀딱이라는 말은 쓰면 안 되는 비속어입니다."
]

predict_discrimination(test_sentences)